sudo: required

services:
  - docker

beofre_install:
  - docker build -t gabstone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gabstone/react-test npm test

after_success:
  # Build images
  - docker build -t gabstone/fib-client ./client
  - docker build -t gabstone/fib-nginx ./nginx
  - docker build -t gabstone/fib-server ./server
  - docker build -t gabstone/fib-worker ./worker

  # Docker CLI Login
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push gabstone/fib-client
  - docker push gabstone/fib-nginx
  - docker push gabstone/fib-server
  - docker push gabstone/fib-worker


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fib-calculator"
  env: "ProdReadyReactApp-env"
  bubcket_name: "elasticbeanstalk-us-east-1-837062711494"
  bucket_path: "fib-calculator"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY